version: '3.8'
services:
    aher:
      container_name: aher
      image: fargeo/aher
      build:
        context: ..
        dockerfile: arches_her/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/arches_her
      env_file:
        - ./docker/env_file.env
      ports:
        - 8002:8000
        - 5678:5678
      depends_on:
        - db_aher
        - elasticsearch_aher
        - couchdb_aher
      stdin_open: true
      tty: true

    aher_livereload:
      profiles:
        - livereload
      container_name: aher_livereload
      image: fargeo/aher
      build:
        context: ..
        dockerfile: aher/Dockerfile
      command: run_livereload
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/arches_her
      env_file:
        - ./docker/env_file.env
      ports:
        - 35729:35729      
      depends_on:
          - aher
      stdin_open: true
      tty: true

    db_aher:
      container_name: db_aher
      image: kartoza/postgis:12.0
      volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-log:/var/log/postgresql
          - ../arches/arches/install/init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
      ports:
        - '5433:5432'
      env_file: 
        - ./docker/env_file.env

    couchdb_aher:
      container_name: couchdb_aher
      image: couchdb:2.1.1
      ports:
        - "5985:5984"
      env_file: 
        - ./docker/env_file.env
      volumes:
        - couchdb-data:/usr/local/var/lib/couchdb
        - couchdb-log:/usr/local/var/log/couchdb

    elasticsearch_aher:
      container_name: elasticsearch_aher
      image: elasticsearch:7.9.2
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9201:9200"
        - "9301:9300"
      env_file: 
        - ./docker/env_file.env

    rabbitmq_aher:
      container_name: rabbitmq_aher
      image: rabbitmq:3-management
      hostname: my-rabbit
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - rabbitmq-logs:/var/log/rabbitmq/log
      ports:
        - 5673:5672
        - 15673:15672

    koop_aher:
      container_name: koop_aher
      image: ryana86/arches-koop:1.0
      ports:
        - 3000:3000
      volumes:
      - ./arches_her/pkg/koop:/usr/src/app/config
      env_file:
        - ./docker/env_file.env
      depends_on:
        - aher
    

volumes:
    arches-log:
    arches-static:
    couchdb-data:
    couchdb-log:
    postgres-data:
    postgres-log:
    elasticsearch-data:
    rabbitmq-logs:
    rabbitmq-data:
